spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      data-locations: classpath:/inventory_seed.sql

  modulith:
    republish-outstanding-events-on-restart: false